"""
Django settings for OM_project project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6tb6+gyo0l60c(!r%hp$x*i=d-c=h5+16pi7ik#eb6h+kx1wg*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'onlinemarketplace100.herokuapp.com', 
    '127.0.0.1'
]

CORS_ORIGIN_ALLOW_ALL = True    # ZMIENIC POTEM NA TO CO JEST NA DOLE NOTE !!! TODO
# CORS_ORIGIN_WHITELIST = (
#     'hostname.example.com'
# )


# Application definition

INSTALLED_APPS = [
    'OM_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',   # this needs to be placed above CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OM_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OM_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = { 
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'django_online_marketplace',
        'USER': 'dbDjangoUser',
        'PASSWORD': 'SDk83Y1HhVQWWZII',
        'HOST': 'mongodb+srv://dbDjangoUser:SDk83Y1HhVQWWZII@cluster0.oo079.mongodb.net/django_online_marketplace?retryWrites=true&w=majority',
        "authMechanism": 'SCRAM-SHA-1',
    }
}

# E-mail/ SMTP

EMAIL_USE_TLS = True    # Transport Layer Security, successor of SSL, used to establish secure connection between web server and client
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'onlinemarketplace100@gmail.com'
EMAIL_HOST_PASSWORD = 'OM@13568'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'OM_app.User'

JWT_AUTH = {
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'OM_app.auth.my_jwt_response_handler',
    'JWT_EXPIRATION_DELTA': datetime.timedelta(minutes=30)      # ZMIENIC CZAS!!!!! TODO co tyle czasu wygasa token i jest potem info w json'ie ze wygasl
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pl-pl'
# Central European Time Zone
TIME_ZONE = 'CET'

USE_I18N = True

USE_L10N = True
# stores datetime information in UTC in database and uses time-zone-aware datetime objects internally, translates them to the end user's time zone
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
