# Generated by Django 3.0.5 on 2020-11-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(null=True, upload_to='offers_images'),
        ),
    ]
