# Generated by Django 3.0.5 on 2020-10-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='city_id',
            field=models.PositiveIntegerField(),
        ),
    ]
