# Generated by Django 3.0.5 on 2020-11-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffercategory',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
