# Generated by Django 3.0.5 on 2020-11-08 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.PositiveIntegerField()),
                ('category_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=30)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('company', models.CharField(max_length=30, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
