# Generated by Django 3.0.5 on 2020-10-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0002_auto_20201028_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='decription',
            new_name='description',
        ),
    ]
