# Generated by Django 3.0.5 on 2020-10-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0002_voivodeship'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('voivodeship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OM_app.Voivodeship')),
            ],
        ),
    ]
