# Generated by Django 3.0.5 on 2020-11-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0002_auto_20201109_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='joboffercategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
