# Generated by Django 3.0.5 on 2020-11-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0003_auto_20201109_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='max_salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
