# Generated by Django 3.0.5 on 2020-11-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0003_joboffercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='remote',
            field=models.BooleanField(default=False),
        ),
    ]
