# Generated by Django 3.0.5 on 2020-11-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0003_auto_20201103_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='add_image1',
            field=models.ImageField(blank=True, upload_to='offers_images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='add_image2',
            field=models.ImageField(blank=True, upload_to='offers_images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='add_image3',
            field=models.ImageField(blank=True, upload_to='offers_images/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='add_image4',
            field=models.ImageField(blank=True, upload_to='offers_images/'),
        ),
    ]
