# Generated by Django 3.0.5 on 2020-11-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0004_auto_20201103_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='add_image1',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='add_image2',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='add_image3',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='add_image4',
        ),
    ]
