# Generated by Django 3.0.5 on 2020-11-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0004_auto_20201110_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='max_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
