# Generated by Django 3.0.5 on 2020-11-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0004_joboffer_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffercategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
