# Generated by Django 3.0.5 on 2020-10-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0005_offerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OM_app.City'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='decription',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
