# Generated by Django 3.0.5 on 2020-11-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0005_auto_20201110_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritejoboffer',
            old_name='favourite',
            new_name='job_offer_id',
        ),
        migrations.RenameField(
            model_name='favouriteoffer',
            old_name='favourite',
            new_name='offer_id',
        ),
    ]
