# Generated by Django 3.0.5 on 2020-10-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0006_auto_20201027_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferImage',
        ),
    ]
