# Generated by Django 3.0.5 on 2020-11-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0006_auto_20201108_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
