# Generated by Django 3.0.5 on 2020-11-10 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0006_auto_20201110_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritejoboffer',
            name='job_offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OM_app.JobOffer', unique=True),
        ),
        migrations.AlterField(
            model_name='favouriteoffer',
            name='offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OM_app.Offer', unique=True),
        ),
    ]
