# Generated by Django 3.0.5 on 2020-11-08 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OM_app', '0007_auto_20201108_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='min_salary',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
